name: Code for DC
url: http://codefordc.org
markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-sitemap
collections:
    docs:
        output: true
    guides:
        output: true
    tools:
        output: true
